// Package shelltest holds the interface the conformance adapter's class
// toggle uses, so its empty shell is generated by yaft-shell rather than
// written by hand: the suite's "empty-shell" case then checks the generator.
package shelltest

//go:generate go run ../../cmd/yaft-shell -type Which

// Which reports which implementation answered.
type Which interface {
	Which() string
}
