// Code generated by yaft-shell; DO NOT EDIT.

package shelltest

// NoopWhich is the empty shell for Which: every method returns nothing. Pass NewNoopWhich as
// the fallback of yaft.Choose for a class toggle without one of its own.
type NoopWhich struct{}

// NewNoopWhich returns the empty shell as a Which.
func NewNoopWhich() Which { return NoopWhich{} }

// Which returns nothing.
func (NoopWhich) Which() (r0 string) {
	return
}
